version: 0.0
os: linux
files:
  - source: dist
    destination: /home/ubuntu/www/
  - source: package.json
    destination: /home/ubuntu/www/package.json

permissions:
  - object: /home/ubuntu/www/
    pattern: '**'
    owner: ubuntu

hooks:
  ApplicationStop:
    - location: scripts/kill_process.sh
      timeout: 60
      runas: ubuntu

  AfterInstall:
    - location: scripts/start_process.sh
      timeout: 120
      runas: ubuntu
